# Generated by Django 4.2.2 on 2023-08-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='ARTICULOS',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='PROVEEDOR',
        ),
        migrations.DeleteModel(
            name='articulosCompra',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
