# Generated by Django 4.2.2 on 2023-08-27 07:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos de la compra',
            },
        ),
        migrations.CreateModel(
            name='gastosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO', models.CharField(max_length=255)),
                ('USER', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCTO', models.CharField(max_length=120)),
                ('DETALLE', models.TextField(blank=True, null=True)),
                ('STOCK', models.IntegerField(blank=True, default=0, null=True)),
                ('CANTIDAD', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('UNIDAD_MEDIDA_COMPRA', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilogramos', 'Kilogramos'), ('Litros', 'Litros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('PRECIO_COMPRA', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('UNIDAD_MEDIDA_USO', models.CharField(choices=[('Unidades', 'Unidades'), ('Gramos', 'Gramos'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Libras', 'Libras')], default='Unidades', max_length=10)),
                ('COSTO_UNITARIO', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('PRECIO_VENTA_UNITARIO', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('USER', models.CharField(blank=True, max_length=120, null=True)),
                ('PROVEEDOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('CODIGO', models.AutoField(primary_key=True, serialize=False, verbose_name='LOTE')),
                ('NOMBRE', models.CharField(max_length=120, verbose_name='PRODUCTO')),
                ('PORCIONES', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('DETALLE', models.TextField(blank=True, null=True)),
                ('RENTABILIDAD', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('RENTABILIDAD_POR_PORCION', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('PRECIO_VENTA', models.DecimalField(decimal_places=2, default=1, max_digits=22)),
                ('PRECIO_VENTA_PORCION', models.DecimalField(decimal_places=2, default=1, max_digits=22)),
                ('COSTO_FINAL', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateTimeField(auto_now=True)),
                ('ARTICULOS', models.TextField(blank=True, null=True)),
                ('GASTOS_ADICIONALES', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True, verbose_name='TOTAL ADICIONALES')),
                ('USER', models.CharField(blank=True, max_length=120, null=True)),
                ('ADICIONALES', models.ManyToManyField(blank=True, to='fabrica.gastosadicionales')),
                ('CATEGORIA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria')),
                ('INGREDIENTES', models.ManyToManyField(to='fabrica.insumo')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('FECHA', models.DateField(default=datetime.date.today)),
                ('CODIGO', models.AutoField(primary_key=True, serialize=False, verbose_name='LOTE')),
                ('ESTADO', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=50)),
                ('FECHA_ENTREGA', models.DateField()),
                ('DETALLES_ADICIONALES', models.TextField(blank=True, null=True)),
                ('COSTO_FINAL', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True)),
                ('USER', models.CharField(blank=True, max_length=120, null=True)),
                ('ARTICULOS', models.ManyToManyField(related_name='articulo_orden', to='fabrica.insumo')),
                ('CLIENTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='ingredientereceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('medida_uso', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.receta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos incluidos en la receta',
            },
        ),
        migrations.CreateModel(
            name='Compra_insumo',
            fields=[
                ('FECHA', models.DateField(default=datetime.date.today)),
                ('CODIGO', models.AutoField(primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Controlada', 'Controlada')], default='Pendiente', max_length=50)),
                ('MEDIO_DE_PAGO', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Cuenta Corriente', 'Cuenta Corriente')], default='Efectivo', max_length=50)),
                ('DETALLES_ADICIONALES', models.TextField(blank=True, null=True)),
                ('COSTO_FINAL', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, null=True)),
                ('USER', models.CharField(blank=True, max_length=120, null=True)),
                ('ARTICULOS', models.ManyToManyField(related_name='articulos_compra', through='fabrica.articulosCompra', to='fabrica.insumo')),
                ('PROVEEDOR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras de insumos',
            },
        ),
        migrations.CreateModel(
            name='articulosOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('Orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.orden')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta_orden', to='fabrica.receta')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos de la Orden',
            },
        ),
        migrations.AddField(
            model_name='articuloscompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.compra_insumo'),
        ),
        migrations.AddField(
            model_name='articuloscompra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.insumo'),
        ),
        migrations.CreateModel(
            name='adicionalreceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.gastosadicionales')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrica.receta')),
            ],
        ),
    ]
