# Generated by Django 4.2.2 on 2023-08-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_gastosadicionales_alter_cliente_options'),
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionalreceta',
            name='adicional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.gastosadicionales'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='ADICIONALES',
            field=models.ManyToManyField(blank=True, to='administracion.gastosadicionales'),
        ),
        migrations.DeleteModel(
            name='gastosAdicionales',
        ),
    ]
