# Generated by Django 4.2.2 on 2023-08-27 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0002_alter_adicionalreceta_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='ULTIMA_ACTUALIZACION',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
