# Generated by Django 4.2.2 on 2023-08-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0003_insumo_ultima_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='ARTICULOS',
            field=models.ManyToManyField(related_name='articulo_orden', related_query_name='articulos', to='fabrica.insumo'),
        ),
    ]
