# Generated by Django 4.2.2 on 2023-09-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0005_alter_orden_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='RENTABILIDAD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='RENTABILIDAD_POR_PORCION',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
