# Generated by Django 4.2.2 on 2023-08-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_insumoscompra_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras de inventario'},
        ),
    ]
