# Generated by Django 4.2.2 on 2023-08-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloscompra',
            name='actualizar_inventario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articuloscompra',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Precio Unitario'),
        ),
    ]
