# Generated by Django 4.2.2 on 2023-08-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0005_alter_orden_articulos'),
        ('compras', '0006_alter_insumoscompra_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumoscompra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='fabrica.insumo'),
        ),
    ]
